name: "BudapestMetroDisplay"
description: "Backgorund service for a BudapestMetroDisplay hardware LED display"
url: "https://github.com/denes44/BudapestMetroDisplay/tree/main/software/ha_addon"
version: "0.1.0"
slug: "budapestmetrodisplay"
init: false
image: "ghcr.io/home-assistant/{arch}-base-python"
version: "3.12"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
ports:
  5000/tcp: 5000
  5568/udp: 5568
options:
  LED_DIM_RATIO: 0.25
  LED_FADE_TIME: 1.0
  SACN_MULTICAST: True
  SACN_UNICAST_IP: 
  SACN_UNIVERSE: 1
  SACN_FPS: 60
  BKK_API_KEY: null
  BKK_API_UPDATE_INTERVAL: 2
  BKK_API_UPDATE_REALTIME: 60
  BKK_API_UPDATE_REGULAR: 1800
  BKK_API_UPDATE_ALERTS: 600
  ESPHOME_USED: False
  ESPHOME_DEVICE_IP: null
  ESPHOME_API_KEY: null
schema:
  LED_DIM_RATIO: float(0,1)
  LED_FADE_TIME: float(0,)
  SACN_MULTICAST: bool
  SACN_UNICAST_IP: "str?"
  SACN_UNIVERSE: "int(1,63999)"
  SACN_FPS: "int(1,)"
  BKK_API_KEY: "str(1,)"
  BKK_API_UPDATE_INTERVAL: "int(1,)"
  BKK_API_UPDATE_REALTIME: "int(1,)"
  BKK_API_UPDATE_REGULAR: "int(1,)"
  BKK_API_UPDATE_ALERTS: "int(1,)"
  ESPHOME_USED: bool
  ESPHOME_DEVICE_IP: "str?" 
  ESPHOME_API_KEY: "str?"
