esphome:
  name: ${name}
  friendly_name: ${friendly_name}

mdns:
  disabled: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_encryption_key
  reboot_timeout: 60min

ota:
  platform: esphome
  password: !secret esphome_ota_pass
  id: my_ota

time:
  - platform: homeassistant
    id: homeassistant_time
