binary_sensor:
  - platform: status
    name: Status

button:
  - platform: restart
    name: Restart
    id: _restart
  - platform: safe_mode
    name: Restart (Safe Mode)
    id: _restart_safe
  - platform: shutdown
    name: Shutdown
    id: _shutdown
