###################################################
# BudapestMetroDisplay ESPHOME created by denes44 #
# https://github.com/denes44/BudapestMetroDisplay #
# Home Assistant update functionately             #
###################################################

ota:
  - platform: esphome
    id: esphome_ota_component

esphome:
  on_boot:
    priority: -100
    then:
      - script.execute: check_update

wifi:
  on_connect:
    then:
      - script.execute: check_update

interval:
  - interval: 6hours
    then:
      - script.execute: check_update

http_request:

text_sensor:
  - platform: template
    name: Remote YAML Update
    id: remote_update_status
    entity_category: diagnostic
    web_server:
      sorting_weight: 1
      sorting_group_id: sg_firmware
    update_interval: never

script:
  - id: check_update
    then:
      - http_request.get:
          url: https://raw.githubusercontent.com/denes44/BudapestMetroDisplay/refs/heads/main/esphome/firmware/manifest.json
          capture_response: true
          on_response:
            then:
              - lambda: |-
                  json::parse_json(body, [](JsonObject root) -> bool {
                      if (root["version"] == to_string(ESPHOME_PROJECT_VERSION)) {
                        id(remote_update_status).publish_state("NO UPDATE");
                      } else {
                        id(remote_update_status).publish_state("UPDATE AVAILABLE");
                      }
                      return true;
                  });
