name: Validate Markdown

on: [push, pull_request]

jobs:
  lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: tj-actions/changed-files@v45
      id: changed-files
      with:
        files: '**/*.md'
        separator: ","
    - uses: DavidAnson/markdownlint-cli2-action@v17
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ","
        fix: true
        config: '.github/rules/custom.markdownlint.jsonc'
  # markdown-link-check:
    # name: Check links
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v4
    # - uses: gaurav-nelson/github-action-markdown-link-check@v1
